fix: replace certbot to acme.sh

diff --git a/http/rootfs/etc/cont-init.d/10-config b/http/rootfs/etc/cont-init.d/10-config
--- a/http/rootfs/etc/cont-init.d/10-config
+++ b/http/rootfs/etc/cont-init.d/10-config
@@ -10,10 +10,46 @@ mkdir -p \
 # generate keys (maybe)
 if [[ $DISABLE_HTTPS -ne 1 ]]; then
     if [[ $ENABLE_LETSENCRYPT -eq 1 ]]; then
-        while [[ ! -f /etc/letsencrypt/live/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; do
-            sleep 15
-        done
-        echo "using keys found in /etc/letsencrypt/liv/$LETSENCRYPT_DOMAIN"
+        if [[ ! -f /config/acme.sh/acme.sh ]]; then
+            mkdir -p /config/acme.sh
+            pushd /opt
+            sh ./acme.sh --install --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL
+            popd
+        fi
+
+        export LE_WORKING_DIR="/config/acme.sh"
+        if [[ ! -f /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ]]; then
+            # TODO: move away from standalone mode to webroot mode.
+            /config/acme.sh/acme.sh \
+                --issue \
+                --standalone \
+                --pre-hook "if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi" \
+                --post-hook "if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi" \
+                -d $LETSENCRYPT_DOMAIN
+            rc=$?
+            if [[ $rc -eq 1 ]]; then
+                echo "Failed to obtain a certificate from the Let's Encrypt CA."
+                # this tries to get the user's attention and to spare the
+                # authority's rate limit:
+                sleep 15
+                echo "Exiting."
+                exit 1
+            fi
+            if [[ $rc -eq 0 ]]; then
+                mkdir -p /config/acme-certs/$LETSENCRYPT_DOMAIN
+                if ! /config/acme.sh/acme.sh \
+                        --install-cert -d $LETSENCRYPT_DOMAIN \
+                        --key-file /config/acme-certs/$LETSENCRYPT_DOMAIN/key.pem \
+                        --fullchain-file /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem ; then
+                    echo "Failed to install certificate."
+                    # this tries to get the user's attention and to spare the
+                    # authority's rate limit:
+                    sleep 15
+                    echo "Exiting."
+                    exit 1
+                fi
+            fi
+        fi
     else
         # use self-signed certs
         until [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; do
